# Dimensión Novedad (dim_novedad) - Fast and Safe ETL

# Imports

In [1]:
from datetime import date

import pandas as pd
import yaml
from sqlalchemy import String, create_engine, text
import hashlib

In [2]:
with open("../config.yml", "r") as f:
    config = yaml.safe_load(f)

config_co = config["CO_SA"]
config_etl = config["ETL_PRO"]

co_sa = create_engine(
    f"{config_co['drivername']}://{config_co['user']}:{config_co['password']}@{config_co['host']}:{config_co['port']}/{config_co['dbname']}"
)

etl_conn = create_engine(
    f"{config_etl['drivername']}://{config_etl['user']}:{config_etl['password']}@{config_etl['host']}:{config_etl['port']}/{config_etl['dbname']}"
)

# Leer tablas origen

df_tipo = pd.read_sql_table(
    "mensajeria_tiponovedad",
    con=co_sa
)

df_novedad = pd.read_sql_table(
    "mensajeria_novedadesservicio",
    con=co_sa
)

print("mensajeria_tiponovedad: ", df_tipo.shape)
print("mensajeria_novedadesservicio: ", df_novedad.shape)

display(df_tipo.head())
display(df_novedad.head())

mensajeria_tiponovedad:  (2, 2)
mensajeria_novedadesservicio:  (5208, 7)

   id                  nombre
0   2      No puedo continuar
1   1  Novedades del servicio

,id,fecha_novedad,tipo_novedad_id,descripcion,servicio_id,es_prueba,mensajero_id
0,4,2023-11-30 05:00:00+00:00,1,A,51,True,7
1,5,2023-11-30 05:00:00+00:00,1,Halo,51,True,7
2,6,2023-11-30 05:00:00+00:00,1,A,51,True,7
3,7,2023-11-30 05:00:00+00:00,1,B,51,True,7
4,8,2023-11-30 05:00:00+00:00,1,A,51,True,7

In [3]:
df = pd.read_sql_table("mensajeria_tiponovedad", con=co_sa)

print(df.columns.tolist())

display(df.head())

['id', 'nombre']

   id                  nombre
0   2      No puedo continuar
1   1  Novedades del servicio

## Transformacion

In [ ]:
# =====================================================
# Construcción de la dimensión novedad
# =====================================================

# unir tipo de novedad con las novedades registradas

dim_novedad = df_novedad.merge(
    df_tipo,
    left_on="tipo_novedad_id",
    right_on="id",
    how="left"
)

# seleccionar atributos

dim_novedad = dim_novedad[
    [
        "tipo_novedad_id",
        "nombre",
        "descripcion"
    ]
].copy()

dim_novedad.columns = [
    "id_novedad",
    "categoria_novedad",
    "descripcion_novedad"
]

# eliminar únicamente registros exactamente iguales

dim_novedad = (
    dim_novedad
    .drop_duplicates()
    .reset_index(drop=True)
)

# surrogate key

dim_novedad.insert(
    0,
    "key_dim_novedad",
    range(1, len(dim_novedad)+1)
)

   key_dim_novedad  id_novedad       categoria_novedad descripcion_novedad
0                1           2      No puedo continuar                   V
1                2           1  Novedades del servicio                   A

## Validaciones

In [5]:
print(dim_novedad.shape)
print(dim_novedad)

print(
    dim_novedad["id_novedad"].duplicated().sum()
)

(2, 4)
   key_dim_novedad  id_novedad       categoria_novedad descripcion_novedad
0                1           2      No puedo continuar                   V
1                2           1  Novedades del servicio                   A
0

## Creamos la tabla

In [6]:
sql = """
DROP TABLE IF EXISTS dim_novedad;

CREATE TABLE dim_novedad(

    key_dim_novedad INTEGER PRIMARY KEY,

    id_novedad INTEGER NOT NULL,

    categoria_novedad VARCHAR(150),

    descripcion_novedad VARCHAR(700)
);
"""

with etl_conn.begin() as conn:
    conn.execute(text(sql))

print("Tabla creada correctamente.")

Tabla creada correctamente.

## Carga

In [7]:
dim_novedad.to_sql(
    "dim_novedad",
    con=etl_conn,
    if_exists="append",
    index=False
)

print("Dimensión cargada.")

Dimensión cargada.